create table if not exists public.sicetac_vacio_vigentes (
    id bigint generated by default as identity primary key,
    mes_vigencia date not null,
    mes_codigo integer not null,
    rutasid text not null,
    ruta text,
    origen text not null,
    nomorigen text not null,
    destino text not null,
    nomdestino text not null,
    configuracion text not null,
    condicion_carga text not null default 'VACIO'
        check (condicion_carga = 'VACIO'),
    tipo_carga_nombre text not null default 'Sin carga'
        check (tipo_carga_nombre = 'Sin carga'),
    estacas_vacio double precision,
    furgon_vacio double precision,
    estibas_vacio double precision,
    plataforma_vacio double precision,
    portacontenedores_vacio double precision,
    furgon_refrigerado_vacio double precision,
    volco_vacio double precision,
    tanque_vacio double precision,
    valorhora_vacio double precision not null default 0,
    archivo_origen text,
    fecha_corte_archivo date not null,
    created_at timestamp with time zone not null default now(),
    constraint sicetac_vacio_vigentes_mes_ruta_config_key
        unique (mes_vigencia, rutasid, configuracion)
);

comment on table public.sicetac_vacio_vigentes is
    'Valores SICETAC oficiales vigentes para viajes sin carga, una fila por ruta y configuracion; las carrocerias se conservan en columnas.';
comment on column public.sicetac_vacio_vigentes.valorhora_vacio is
    'Valor hora publicado por la fuente para VACIO; en el corte 2026-07-15 es cero.';
comment on column public.sicetac_vacio_vigentes.portacontenedores_vacio is
    'Viaje del vehiculo portacontenedores sin carga ni contenedor. No equivale a transportar un contenedor vacio.';

create index if not exists sicetac_vacio_vigentes_od_config_mes_idx
    on public.sicetac_vacio_vigentes
    (origen, destino, configuracion, mes_codigo desc);

alter table public.sicetac_vacio_vigentes enable row level security;

revoke all on table public.sicetac_vacio_vigentes from public, anon, authenticated;
grant select, insert, update, delete on table public.sicetac_vacio_vigentes to service_role;
grant usage, select on sequence public.sicetac_vacio_vigentes_id_seq to service_role;

notify pgrst, 'reload schema';
